service: mern-application

# custom:
#   tableName: "ideas-table"

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: prod
  timeout: 6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
        - Fn::Join:
            - "/"
            - - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
              - "index/*"
  environment:
    USERS_TABLE: USERS_TABLE
    USERS_INDEX: USERS_INDEX

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
resources:
  Resources:
    UsersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: USERS_INDEX
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - salted_password
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "USERS_TABLE"
